# Generated by Django 2.1.15 on 2020-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appid', models.IntegerField()),
                ('AppNames', models.CharField(max_length=200)),
            ],
        ),
    ]
